/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wingdom' at '2/12/17 10:54 AM' with Gradle 2.14.1
 *
 * @author Cameron Yeager, @date 2/12/17 10:54 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
